import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
const migration = await readFile(new URL('../supabase/migrations/20260910190000_create_app_administration.sql', import.meta.url), 'utf8');
const F='00000000-0000-4000-8000-000000000001', K='00000000-0000-4000-8000-000000000002', P='00000000-0000-4000-8000-000000000003';
test('administration permissions, activation, audit and last-admin protection', async () => {
 const db = new PGlite();
 try {
 await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS; CREATE SCHEMA auth;
 CREATE TABLE auth.users(id uuid PRIMARY KEY,email text,encrypted_password text,raw_app_meta_data jsonb DEFAULT '{}',raw_user_meta_data jsonb DEFAULT '{}');
 CREATE TABLE public.user_profiles(user_id uuid); CREATE TABLE public.user_subscriptions(user_id uuid UNIQUE, plan_type text NOT NULL, status text, payment_hash text, current_period_start timestamptz, current_period_end timestamptz, updated_at timestamptz);
 CREATE TABLE public.rounds(id integer); INSERT INTO public.rounds VALUES(42);
 CREATE TABLE public.admin_config(admin_pin text); GRANT ALL ON public.admin_config TO authenticated, anon;
 CREATE FUNCTION auth.jwt() RETURNS jsonb LANGUAGE sql AS $$ SELECT current_setting('request.jwt.claims', true)::jsonb $$;
 CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT (auth.jwt()->>'sub')::uuid $$;
 GRANT USAGE ON SCHEMA auth TO authenticated; GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA auth TO authenticated;
 INSERT INTO auth.users(id,email) VALUES ('${F}','f+admin@example.com'),('${K}','k+admin@example.com'),('${P}','f@example.com');
 INSERT INTO public.user_profiles VALUES('${P}');`);
 await db.exec(migration);
 await db.exec(`CREATE TRIGGER on_auth_user_created_create_subscription AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION create_subscription_from_signup_plan();
 INSERT INTO auth.users(id,email) VALUES ('00000000-0000-4000-8000-000000000010','no-plan@example.com');
 INSERT INTO auth.users(id,email,raw_user_meta_data) VALUES ('00000000-0000-4000-8000-000000000011','team@example.com','{"requested_plan":"team"}');`);
 assert.deepEqual((await db.query('SELECT plan_type FROM user_subscriptions')).rows,[{plan_type:'team'}]);
 await assert.rejects(db.query('SELECT bootstrap_app_administrator($1,$2)',[P,'AdminP']),/separada/);
 await db.query('SELECT bootstrap_app_administrator($1,$2)',[F,'AdminF']);
 await db.query("UPDATE auth.users SET encrypted_password='test-hash-f' WHERE id=$1",[F]);
 await db.query("UPDATE auth.users SET raw_app_meta_data='{\"app_account_type\":\"administrator\"}' WHERE id=$1",[K]);
 await db.query('SELECT register_app_administrator($1,$2,$3)',[F,K,'AdminK']);
 const as = async id => {await db.exec('RESET ROLE');await db.query("SELECT set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:id,session_id:'00000000-0000-4000-8000-000000000099'})]);await db.exec('SET ROLE authenticated');};
 await as(P);
 assert.equal((await db.query('SELECT get_my_app_administrator() AS account')).rows[0].account,null);
 for (const sql of ['SELECT * FROM app_administrators','SELECT * FROM app_admin_audit','SELECT * FROM admin_config','SELECT list_app_administrators()','SELECT list_app_admin_audit()','SELECT record_app_admin_login()',`SELECT bootstrap_app_administrator('${P}','AdminP')`,`SELECT register_app_administrator('${F}','${P}','AdminP')`,`SELECT record_app_admin_invitation_sent('${F}','${K}')`,`UPDATE app_administrators SET status='active'`]) await assert.rejects(db.exec(sql));
 await as(F);
 assert.equal((await db.query('SELECT * FROM list_app_administrators()')).rows.length,2);
 await db.exec('SELECT record_app_admin_login(); SELECT record_app_admin_login();');
 assert.equal((await db.query("SELECT * FROM list_app_admin_audit() WHERE action='administrator.login'")).rows.length,1);
 await assert.rejects(db.query('SELECT set_app_administrator_active($1,false,$2)',[F,'prueba']),/último/);
 await db.exec('RESET ROLE');await db.query("UPDATE auth.users SET encrypted_password='test-hash-k' WHERE id=$1",[K]);
 await as(F);await db.query('SELECT set_app_administrator_active($1,false,$2)',[K,'Prueba de bloqueo']);
 const events=(await db.query('SELECT * FROM list_app_admin_audit()')).rows;
 const change=events.find(e=>e.action==='administrator.status_changed');
 assert.equal(change.actor_user_id,F);assert.equal(change.details.after,'disabled');assert.equal(change.details.before,'active');
 assert.ok(!JSON.stringify(events).includes('test-hash'));
 await as(K);await assert.rejects(db.exec('SELECT list_app_administrators()'),/denegado/);
 await assert.rejects(db.query('SELECT set_app_administrator_active($1,true,$2)',[K,'Reactivar']),/denegado/);
 await db.exec('RESET ROLE');await assert.rejects(db.query("UPDATE auth.users SET encrypted_password='new' WHERE id=$1",[K]),/desactivada/);
 await as(F);await db.query('SELECT set_app_administrator_active($1,true,$2)',[K,'Reactivación']);
 await as(K);assert.equal((await db.query('SELECT * FROM list_app_administrators()')).rows.length,2);
 await db.exec('RESET ROLE');assert.deepEqual((await db.query('SELECT * FROM rounds')).rows,[{id:42}]);
 await assert.rejects(db.query('SELECT bootstrap_app_administrator($1,$2)',[P,'AdminP']),/ya existe/);
 } finally {await db.close();}
});
