import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { PGlite } from '@electric-sql/pglite';
import { createGroupDatabase } from './helpers/group-database.mjs';

test('group identities, isolated handicaps, protected lifecycle and round snapshots', async () => {
 const db = new PGlite();
 const [owner, member, outsider, group, otherGroup, legacy, roundId] = Array.from({length:7}, randomUUID);
 try {
 await createGroupDatabase(db);
 await db.exec(`
 INSERT INTO auth.users VALUES('${owner}'),('${member}'),('${outsider}');
 INSERT INTO user_profiles VALUES('${owner}','FedeTeam','Fede',NULL,0),('${member}','Fede','Federico',NULL,18);
 INSERT INTO groups VALUES('${group}','${owner}'),('${otherGroup}','${owner}');
 INSERT INTO group_members(group_id,user_id,role) VALUES('${group}','${member}','member'),('${otherGroup}','${member}','member');
 INSERT INTO players(id,group_id,name,exact_handicap,exact_handicap_18) VALUES('${legacy}','${group}','Fede',7,7);
 GRANT USAGE ON SCHEMA public,auth TO anon,authenticated;
 GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO anon,authenticated;
 `);
 await db.exec(await readFile(new URL('../supabase/migrations/20260917100000_group_member_players.sql',import.meta.url),'utf8'));
 const as = async id => {await db.exec('RESET ROLE');await db.query("SELECT set_config('request.uid',$1,false)",[id||'']);await db.exec(`SET ROLE ${id?'authenticated':'anon'}`);};
 const roster = async g => (await db.query('SELECT list_identified_group_members($1) value',[g])).rows[0].value;
 const change = (m,action,hcp=null) => db.query('SELECT manage_group_member($1,$2,$3,$4,$5,$6)',[m.group_id,m.user_id,m.member_revision,m.player_revision,action,hcp]);
 await as(owner);
 let m=(await roster(group)).find(x=>x.user_id===member);
 assert.equal(m.profile.nick,'Fede');assert.equal(m.handicap_18,18);assert.notEqual(m.player_id,legacy);
 assert.deepEqual(Object.keys(m.profile).sort(),['avatar_url','display_name','nick']);
 const zero=(await roster(group)).find(x=>x.user_id===owner);assert.equal(zero.handicap_18,0);
 await change(m,'handicap',0);
 await assert.rejects(change(m,'handicap',5),/ha cambiado/);
 m=(await roster(group)).find(x=>x.user_id===member);assert.equal(m.handicap_18,0);
 assert.equal((await roster(otherGroup)).find(x=>x.user_id===member).handicap_18,18);
 await db.query('UPDATE user_profiles SET exact_handicap=40 WHERE user_id=$1',[member]);
 assert.equal((await roster(otherGroup)).find(x=>x.user_id===member).handicap_18,18);
 await assert.rejects(db.query('UPDATE players SET exact_handicap=20 WHERE id=$1',[m.player_id]),/operación autorizada/);
 await assert.rejects(db.query('DELETE FROM players WHERE id=$1',[m.player_id]),/conservan/);
 await assert.rejects(db.query("INSERT INTO group_write_permits VALUES(txid_current(),$1,'player')",[m.player_id]),/permission denied/);
 await change(m,'handicap',18.5);m=(await roster(group)).find(x=>x.user_id===member);
 await db.query('INSERT INTO golf_rounds(id,group_id,num_holes,use_slope) VALUES($1,$2,18,false)',[roundId,group]);
 await db.query("INSERT INTO round_players(round_id,player_id,name,exact_handicap,playing_handicap) VALUES($1,$2,'Fede',9.25,99)",[roundId,m.player_id]);
 let snapshot=(await db.query('SELECT * FROM round_players')).rows[0];assert.equal(snapshot.user_id,member);assert.equal(Number(snapshot.playing_handicap),19);
 await change(m,'handicap',24);m=(await roster(group)).find(x=>x.user_id===member);
 assert.equal(Number((await db.query('SELECT exact_handicap FROM round_players')).rows[0].exact_handicap),9.25);
 await assert.rejects(change(zero,'remove'),/propietario/);
 await as(outsider);await assert.rejects(roster(group),/acceso/);await assert.rejects(change(m,'handicap',12),/permiso/);
 await as(member);await assert.rejects(change(m,'handicap',12),/permiso/);
 await as(owner);await db.query('INSERT INTO app_user_restrictions VALUES($1,true)',[owner]);await assert.rejects(change(m,'remove'),/permiso/);assert.equal((await roster(group)).length,2);
 await db.query('DELETE FROM app_user_restrictions WHERE user_id=$1',[owner]);
 const invite=randomUUID();await db.query("INSERT INTO group_invitations VALUES($1,$2,$3,$4,'pending',NULL)",[invite,group,member,owner]);
 await as(member);await db.query("SELECT respond_to_group_invitation($1,'accepted')",[invite]);
 await as(owner);await change(m,'remove');
 assert.equal((await roster(group)).length,1);assert.equal((await db.query('SELECT * FROM round_players')).rows.length,1);
 await as(member);await assert.rejects(db.query("SELECT respond_to_group_invitation($1,'accepted')",[invite]),/no disponible/);
 await assert.rejects(db.query("INSERT INTO group_members(group_id,user_id,role) VALUES($1,$2,'member')",[group,member]),/invitación vigente/);
 await as(owner);const nextInvite=randomUUID();await db.query("INSERT INTO group_invitations VALUES($1,$2,$3,$4,'pending',NULL)",[nextInvite,group,member,owner]);
 await as(member);await db.query("SELECT respond_to_group_invitation($1,'accepted')",[nextInvite]);
 m=(await roster(group)).find(x=>x.user_id===member);assert.equal(m.handicap_18,24);assert.equal(m.player_id,snapshot.player_id);
 await assert.rejects(db.query("UPDATE group_invitations SET status='pending' WHERE id=$1",[nextInvite]),/operación de invitaciones/);
 await as(owner);
 await change(m,'handicap',18);
 await db.query('INSERT INTO round_scores(round_id,player_id,stableford_points,spanish_hands) VALUES($1,$2,20,true)',[roundId,snapshot.id]);
 await as(member);
 await db.query("INSERT INTO archived_rounds(group_id,played_at,final_ranking,player_stats,source_round_id) VALUES($1,now(),$2,'[]',$3)",[group,JSON.stringify([{position:1,player_name:'Fede',player_id:snapshot.id,player_db_id:m.player_id},{position:2,player_name:'Other'}]),roundId]);
 assert.equal((await roster(group)).find(x=>x.user_id===member).handicap_18,20);
 assert.equal((await db.query('SELECT game_player_id FROM daily_rankings')).rows[0].game_player_id,m.player_id);
 assert.equal(Number((await db.query('SELECT exact_handicap FROM players WHERE id=$1',[legacy])).rows[0].exact_handicap),7,'a linked result must never adjust a same-name legacy record');
 await assert.rejects(db.query('UPDATE handicap_adjustments SET hcp_before=27 WHERE player_id=$1',[m.player_id]),/operación autorizada/);
 await assert.rejects(db.query('SELECT apply_handicap_adjustments_for_round($1)',[randomUUID()]),/permission denied/);
 await assert.rejects(db.query('DELETE FROM archived_rounds'),/permiso/);
 await as(owner);
 await db.query("INSERT INTO archived_rounds(group_id,played_at,final_ranking,player_stats) VALUES($1,now(),$2,'[]')",[group,JSON.stringify([{position:1,player_name:'Fede',points:10,hcp_juego:7}])]);
 const separated=(await db.query('SELECT game_player_id,player_name FROM daily_rankings')).rows;
 assert.equal(separated.length,2);assert.ok(separated.some(x=>x.game_player_id===m.player_id));assert.ok(separated.some(x=>x.game_player_id===null));
 await db.query('DELETE FROM archived_rounds');assert.equal((await roster(group)).find(x=>x.user_id===member).handicap_18,18);
 await db.query("INSERT INTO app_administrators VALUES($1,'disabled')",[owner]);
 await assert.rejects(change((await roster(group)).find(x=>x.user_id===member),'handicap',12),/permiso/);
 await db.query('DELETE FROM app_administrators WHERE user_id=$1',[owner]);
 await as(owner);
 const noProfileGroup=randomUUID(); await db.query('INSERT INTO groups VALUES($1,$2)',[noProfileGroup,owner]);
 const pendingInvite=randomUUID(); await db.query("INSERT INTO group_invitations VALUES($1,$2,$3,$4,'pending',NULL)",[pendingInvite,noProfileGroup,outsider,owner]);
 await as(outsider); await db.query("SELECT respond_to_group_invitation($1,'accepted')",[pendingInvite]);
 let pending=(await roster(noProfileGroup)).find(x=>x.user_id===outsider); assert.equal(pending.handicap_18,null);assert.equal(pending.profile,null);
 const pendingRound=randomUUID(); await db.query('INSERT INTO golf_rounds(id,group_id,num_holes,use_slope) VALUES($1,$2,9,false)',[pendingRound,noProfileGroup]);
 await assert.rejects(db.query('INSERT INTO round_players(round_id,player_id,exact_handicap) VALUES($1,$2,0)',[pendingRound,pending.player_id]),/Hándicap pendiente/);
 await as(owner); await change(pending,'handicap',0);pending=(await roster(noProfileGroup)).find(x=>x.user_id===outsider);assert.equal(pending.handicap_18,0);
 await assert.rejects(change(pending,'handicap',55),/entre 0 y 54/);
 await db.query("UPDATE group_members SET role='admin' WHERE group_id=$1 AND user_id=$2",[noProfileGroup,outsider]);
 await as(outsider);const ownerCard=(await roster(noProfileGroup)).find(x=>x.user_id===owner);await change(ownerCard,'handicap',6);
 await as(owner);await db.query("UPDATE group_members SET role='member' WHERE group_id=$1 AND user_id=$2",[noProfileGroup,outsider]);
 await as(outsider);await assert.rejects(change(ownerCard,'handicap',7),/permiso/);await as(owner);
 // A previous membership version is invalid even after removal and rejoining.
 await assert.rejects(change({...m,member_revision:1},'handicap',4),/ha cambiado/);
 await db.exec('RESET ROLE');assert.equal(Number((await db.query('SELECT count(*) n FROM group_write_permits')).rows[0].n),0);
 await as(null);await assert.rejects(roster(group),/permission denied/);
 await db.query("INSERT INTO players(name,exact_handicap) VALUES('Express sin cuenta',4)");
 await db.query("UPDATE players SET exact_handicap=5 WHERE name='Express sin cuenta'");
 assert.equal(Number((await db.query("SELECT exact_handicap FROM players WHERE name='Express sin cuenta'")).rows[0].exact_handicap),5);
 // A server-side audit failure rolls the handicap and version back as well.
 await db.exec('RESET ROLE');
 await db.exec(`CREATE FUNCTION reject_test_audit() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION 'audit unavailable'; END$$;
 CREATE TRIGGER reject_test_audit BEFORE INSERT ON app_admin_audit FOR EACH ROW EXECUTE FUNCTION reject_test_audit();`);
 await as(owner);const before=(await roster(group)).find(x=>x.user_id===member);
 await assert.rejects(change(before,'handicap',53),/audit unavailable/);
 const after=(await roster(group)).find(x=>x.user_id===member);assert.equal(after.handicap_18,before.handicap_18);assert.equal(after.player_revision,before.player_revision);
 } finally {await db.close();}
});
